<?php

namespace ConferenceSchedulerBundle\Repository;

/**
 * ConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveConferences()
    {
        $currentDate = date("Y-m-d");

        return $this->createQueryBuilder('conference')->
        where('conference.startDate >= :startTime')->
        setParameter('startTime', $currentDate)->
        orderBy('conference.startDate')->
        getQuery()->
        getResult();
    }
}
