<?php

namespace ConferenceSchedulerBundle\Repository;
use ConferenceSchedulerBundle\Entity\Conference;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    function getSortedByStartTime(Conference $conference)
    {
        return $this->createQueryBuilder('session')->
            where('session.conference == :conference')->
            setParameter('conference', $conference)->
            orderBy('session.startTime')->
            getQuery()->
            getResult();
    }
}
